/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cgsuite.help;

import java.awt.BorderLayout;
import java.net.URL;
import java.util.Enumeration;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.help.JHelp;
import javax.help.JHelpIndexNavigator;
import javax.help.JHelpNavigator;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.cgsuite.help//CgsuiteHelp//EN",
autostore = false)
@TopComponent.Description(preferredID = "CgsuiteHelpTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "help", openAtStartup = false)
@ActionID(category = "Window", id = "org.cgsuite.help.CgsuiteHelpTopComponent")
@ActionReference(path = "Menu/Window", position = 1750)
@TopComponent.OpenActionRegistration(displayName = "#CTL_CgsuiteHelpAction",
preferredID = "CgsuiteHelpTopComponent")
public final class CgsuiteHelpTopComponent extends TopComponent {

    private JHelp helpViewer;

    public CgsuiteHelpTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(CgsuiteHelpTopComponent.class, "CTL_CgsuiteHelpTopComponent"));
        setToolTipText(NbBundle.getMessage(CgsuiteHelpTopComponent.class, "HINT_CgsuiteHelpTopComponent"));
        URL helpUrl = getClass().getResource("docs/help-hs.xml");
        HelpSet help;
        try {
            help = new HelpSet(getClass().getClassLoader(), helpUrl);
        } catch (HelpSetException exc) {
            throw new RuntimeException(exc);
        }
        helpViewer = new JHelp(help);
        helpViewer.setToolbarDisplayed(false);
        Enumeration e = helpViewer.getHelpNavigators();
        while (e.hasMoreElements())
        {
            JHelpNavigator navigator = (JHelpNavigator) e.nextElement();
            if (navigator instanceof JHelpIndexNavigator)
            {
                helpViewer.removeHelpNavigator(navigator);
                break;
            }
        }
        add(helpViewer, BorderLayout.CENTER);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }
    
    public JHelp getHelpViewer()
    {
        return helpViewer;
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
}
